### ISSUE TITLE
Improve Fastly Compute@Edge Example

### ISSUE THREAD

**Issue by Abiti-936** [fauna-labs/edge-gateway-sample-fastly#1]
Do you know [Worktop's](https://github.com/lukeed/worktop/tree/next) next version has a capability to work with Fastly Compute@Edge & Faunadb JS Driver can Work with Compute@Edge?
Also there are GraphQL Server Frameworks that are Compatible with Edge Environments. [GraphQL Helix](https://www.graphql-helix.com/) & [GraphQL Yoga](https://www.graphql-yoga.com/) are the most Dominant One's.
Could You Update the Example to use Worktop or [FlightPath](https://github.com/williamoverton/FlightPath) & add a GraphQL Example?

**Comment by Abiti-936** [comment]
I don't know why, but AbortController isn't defined in Compute@Edge JS Runtime. How I can Polyfill it?

**Comment by zeekhoo** [comment]
Hi, thats a good idea but Compute@Edge requires outgoing requests to go to a predefined [backend](https://developer.fastly.com/reference/glossary#term-backend) passed in via the __backend__ property through fetch(). Since worktop does not include any utility to pass in that option, I don't think it'll be very useful. Incidentally, the custom fetch() requirement also prevents us from using the Fauna js client.

To help with routing, a good alternative is [itty-router](https://www.npmjs.com/package/itty-router), which should work. For the purposes of this sample, we're limiting use of 3rd party dependencies for maintainability.

**Comment by Abiti-936** [comment]
I have used the fetch option in faunadb JS client instance to set the backend like these:

```js
const client = new faunadb.Client({
  secret: 'your secret',
  fetch: (url, params) => {
    return Promise.race([
      fetch(url, { backend: "faunadb", ...params })
    ])
  },
})
```

What I have an issue with is:
  1. Abort Controller, that I have to polyfill it with [these](https://github.com/mysticatea/abort-controller) library
  2. setTimeout isn't defined in Fastly Compute@Edge, that I have to set timeout Option to undefined in the client instance
  ```js
const client = new faunadb.Client({
    secret: 'your secret',
    timeout: undefined,
    keepAlive: false
});
```

**Comment by ghost** [comment]
Oh, it's treaky to integrate Faunadb JS Driver with Fastly Compute@Edge, but I have a Working Demo.
https://github.com/amancoder28/fauna-rest-compute-edge-example

**Comment by zeekhoo** [comment]
Thanks for all this. The abort-controller polyfill, timeout workaround and custom fetch seems to do the trick. I'll test this out and update the sample if we don't run into any major issues.

**Comment by Abiti-936** [comment]
It will be good if we can polyfill setTimeout. Also What About GraphQL? We can use [GraphQL Yoga](https://www.graphql-yoga.com/) with [Remote Schema Loader](https://www.graphql-tools.com/docs/remote-schemas) or [URL Schema Loader](https://www.graphql-tools.com/docs/schema-loading#url-loader) from [GraphQL Tools](https://www.graphql-tools.com/). I think these approach can also Work without any problems.

**Comment by zeekhoo** [comment]
We don't have a solution yet for setTimeout polyfill.  For GraphQL, there's another sample [here](https://github.com/fauna-labs/fastly-fauna-gql) albeit its in Rust.

**Comment by Abiti-936** [comment]
Oh, It's hard to Read a Rust Code. I will try to implement it with GraphQL Yoga with minimal code & we will see if it's good enough.

**Comment by ghost** [comment]
Wow, it's easy to create a GraphQL Gateway with Fastly Compute@Edge, FaunaDB & GraphQL Yoga.
https://github.com/amancoder28/fauna-graphql-compute-edge-example

**Comment by ghost** [comment]
Please create with-worktop & with-graphql-yoga branches because I need create pull requests without overriding the current implementation.

**Comment by ghost** [comment]
I don't know why but the GraphQL Examples are not Working after Deploying to Fastly Compute@Edge, but they Working on My Machine. Also I have tried them on Cloudflare Workers & the Examples are Working. There is a Serious Problem with Fastly. Please Tell me if they are Working for You.

**Comment by zeekhoo** [comment]
> I don't know why but the GraphQL Examples are not Working after Deploying to Fastly Compute@Edge, but they Working on My Machine. Also I have tried them on Cloudflare Workers & the Examples are Working. There is a Serious Problem with Fastly. Please Tell me if they are Working for You.

There's no GraphQL example in this project. Which are you referring to?

**Comment by ghost** [comment]
In My Github Repos: 
https://github.com/amancoder28/fauna-graphql-compute-edge-example
https://github.com/amancoder28/fauna-graphql-compute-edge-example-2

**Comment by zeekhoo** [comment]
> In My Github Repos: https://github.com/amancoder28/fauna-graphql-compute-edge-example https://github.com/amancoder28/fauna-graphql-compute-edge-example-2

Oh I see. Realize that Cloudflare and Fastly are vastly different runtime environments. Though, I'm not sure why it works locally on not when deployed...you may have to find help from Fastly. None of this is an issue for THIS project though.

**Comment by Abiti-936** [comment]
I Think now we have Solved the Issues that's making Fauna JS Driver not to work in Fastly Compute@Edge. Just Contact me for future Contribution. Thanks.
